-- ex06_db프로젝트에서 쓸 query
--ex1
SELECT * FROM EMP;
--ex2
SELECT DEPTNO, DNAME FROM DEPT;

SELECT E.*, DNAME
    FROM EMP E, DEPT D
    WHERE E.DEPTNO = D.DEPTNO
        AND E.DEPTNO LIKE '%' || ?;
        
SELECT E.*, DNAME
    FROM EMP E, DEPT D
    WHERE E.DEPTNO = D.DEPTNO
        AND E.ENAME LIKE '%'||UPPER(TRIM('S'))||'%';