--[VIII] Sequence : 순차번호 생성기, 인위적인 PK 사용용도
DROP SEQUENCE FRIEND_SEQ;
CREATE SEQUENCE FRIEND_SEQ
    START WITH 1 -- 1부터 시작(기본값)
    INCREMENT BY 1 -- 1씩 증가(기본값)
    MAXVALUE 9999 -- 최대값
    MINVALUE 1 -- 최소값
    NOCACHE
    NOCYCLE;

SELECT FRIEND_SEQ.NEXTVAL FROM DUAL; -- 다음 순차번호 생성
SELECT FRIEND_SEQ.CURRVAL FROM DUAL; -- 시퀀스의 현재값
-- FRIEND테이블(NO - PK, NAME, TEL, ADDRESS, LAST_MODIFY)
DROP SEQUENCE FRIEND_SEQ;
CREATE SEQUENCE FRIEND_SEQ
    MAXVALUE 99999
    NOCACHE
    NOCYCLE;

DROP TABLE FRIEND;

CREATE TABLE FRIEND(
    NO NUMBER(5) PRIMARY KEY,
    NAME VARCHAR2(30) NOT NULL,
    TEL VARCHAR2(20) UNIQUE, -- NULL 허용
    ADDRESS VARCHAR2(255),
    LAST_MODIFY DATE DEFAULT SYSDATE
);

INSERT INTO FRIEND(NO, NAME, TEL, ADDRESS)
    VALUES (FRIEND_SEQ.NEXTVAL, '홍길동', NULL,'서울시 관악구');

SELECT * FROM FRIEND;

INSERT INTO FRIEND(NO, NAME, TEL, ADDRESS)
    VALUES (FRIEND_SEQ.NEXTVAL, NULL, '010-9999-9999','서울시 관악구'); -- 에러 (NOT NULL)
INSERT INTO FRIEND(NO, NAME, TEL, ADDRESS)
    VALUES (FRIEND_SEQ.NEXTVAL, '박길동', '010-9999-9999','서울시 관악구');

--EX2
DROP SEQUENCE FRIEND_SEQ;
CREATE SEQUENCE FRIEND_SEQ
    MAXVALUE 999
    NOCACHE
    NOCYCLE;

DROP TABLE FRIEND;
CREATE TABLE FRIEND(
    NO NUMBER(11) PRIMARY KEY,
    NAME VARCHAR2(30) NOT NULL,
    TEL VARCHAR2(20) UNIQUE, -- NULL 허용
    ADDRESS VARCHAR2(255),
    LAST_MODIFY DATE DEFAULT SYSDATE
);

INSERT INTO FRIEND(NO, NAME, TEL, ADDRESS)
    VALUES (TO_CHAR(SYSDATE, 'YYYYMMDD')||TRIM(TO_CHAR(FRIEND_SEQ.NEXTVAL,'000')), '홍길동', NULL,'서울시 관악구');

SELECT * FROM FRIEND;

-- QUIZ
DROP SEQUENCE MEMBER_mNO_SEQ;
DROP TABLE MEMBER;
DROP TABLE MEMBER_LEVEL;


CREATE TABLE MEMBER_LEVEL (
    LEVELNO NUMBER(1) PRIMARY KEY,
    LEVELNAME VARCHAR(10) NOT NULL
);

CREATE SEQUENCE MEMBER_mNO_SEQ
    MAXVALUE 9
    NOCACHE
    NOCYCLE;

CREATE TABLE MEMBER (
    mNO NUMBER(1) PRIMARY KEY,
    mNAME VARCHAR2(50) NOT NULL,
    mPW  VARCHAR2(8) NOT NULL,
    mMAIL VARCHAR2(225) UNIQUE,
    mPOINT  NUMBER(10) CHECK (mPOINT>=0),
    mRDATE DATE DEFAULT TO_CHAR(SYSDATE, 'RR/MM/DD'),
    LEVELNO NUMBER(1) REFERENCES MEMBER_LEVEL(LEVELNO)
);

INSERT INTO MEMBER_LEVEL
    VALUES (-1,'black');
INSERT INTO MEMBER_LEVEL
    VALUES (0,'일반');
INSERT INTO MEMBER_LEVEL
    VALUES (1,'실버');
INSERT INTO MEMBER_LEVEL
    VALUES (2,'골드');

INSERT INTO MEMBER (mNO, mNAME, mPW, mMAIL, mPOINT, mRDATE, LEVELNO)
    VALUES (TRIM(MEMBER_mNO_SEQ.NEXTVAL), '홍길동', 'aa', 'hong@hong.com', 0, TO_DATE('22/03/10','RR/MM/DD'), 0);
INSERT INTO MEMBER (mNO, mNAME, mPW, mMAIL, mPOINT, mRDATE, LEVELNO)
    VALUES (TRIM(MEMBER_mNO_SEQ.NEXTVAL), '신길동', 'bb', 'sin@sin.com', 1000, TO_DATE('22/04/01'), 1);

SELECT * FROM MEMBER; 

SELECT mNO, mNAME, mMAIL, mPOINT point, LEVELNAME||'고객' levelname
    FROM MEMBER M, MEMBER_LEVEL L
    WHERE M.LEVELNO = L.LEVELNO;





