-- 테이블 제거
DROP TABLE MEMBER CASCADE CONSTRAINTS;
-- 테이블 생성
CREATE TABLE MEMBER(
    ID VARCHAR2(30),
    PW VARCHAR2(30) NOT NULL,
    NAME VARCHAR2(30) NOT NULL,
    BIRTH DATE,
    RDATE DATE DEFAULT SYSDATE NOT NULL,
    PRIMARY KEY(ID)
    );

-- 더미 데이터
INSERT INTO MEMBER (ID, PW, NAME, BIRTH)
    VALUES ('aaa','111','홍길동', TO_DATE('1998-12-12','YYYY-MM-DD'));
INSERT INTO MEMBER (ID, PW, NAME, BIRTH)
    VALUES ('bbb','111','신길동', '01/06/12');
SELECT * FROM MEMBER ORDER BY NAME;
COMMIT;

SELECT COUNT(*) 
    FROM MEMBER 
    WHERE ID = 'AAA';
