DROP TABLE FRIEND;
CREATE TABLE FRIEND(
    NO NUMBER(4) PRIMARY KEY,
    NAME VARCHAR2(24) NOT NULL,
    TEL VARCHAR2(50) UNIQUE
);

DROP SEQUENCE FRIEND_SEQ;
CREATE SEQUENCE FRIEND_SEQ
     START WITH 1 
    INCREMENT BY 1 
    MAXVALUE 9999 
    MINVALUE 1 
    NOCACHE
    NOCYCLE;

INSERT INTO FRIEND VALUES(FRIEND_SEQ.NEXTVAL,'홍길동','010-9999-9999');

SELECT * FROM FRIEND;

COMMIT;